# src/main/resources/application.yml

azure:
  activedirectory:
    tenant-id: ${TENANT_ID}
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    authorization-clients:
      calendar-api:
        scopes:
          - api://b4a92625-b0ea-4a45-bc6f-772d904ae8da/ReadMyCalendar

logging:
  level:
    org:
      springframework:
        security: DEBUG