# src/main/resources/application.yml
azure:
  activedirectory:
    b2c:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}
      logout-success-url: http://localhost:8080
      user-flows:
        sign-up-or-sign-in: B2C_1_signuporsignin
      base-uri: https://${TENANT_NAME}.b2clogin.com/${TENANT_NAME}.onmicrosoft.com/
      login-flow: sign-up-or-sign-in
      reply-url: http://localhost:8080/login/oauth2/code/
