# src/main/resources/application.yml

azure:
  activedirectory:
    tenant-id: ${TENANT_ID}
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    authorization-clients:
      calendar-api:
        scopes:
          - ${CALENDAR_SCOPE}
      azure-api:
        scopes:
          - ${AZURE_SCOPE}

logging:
  level:
    org:
      springframework:
        security: DEBUG