# src/main/resources/application.yml

azure:
  activedirectory:
    tenant-id: ${TENANT_ID}
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}

logging:
  level:
    org:
      springframework:
        security: DEBUG