azure:
  activedirectory:
    b2c:
      client-id: ${CLIENT_ID}
      client-secret: ${CLIENT_SECRET}
      logout-success-url: http://localhost:8080
      user-flows:
        password-reset: B2C_1_resetpassword
        profile-edit: B2C_1_profileedit
        sign-up-or-sign-in: B2C_1_signuporsignin
      base-uri: https://mysampleazureorganization.b2clogin.com/mysampleazureorganization.onmicrosoft.com/
      login-flow: sign-up-or-sign-in
      reply-url: http://localhost:8080/login/oauth2/code/
