azure:
  activedirectory:
    # Specifies your Active Directory ID:
    tenant-id: ${TENANT_ID}
    # Specifies your App Registration's Application ID:
    client-id: ${CLIENT_ID}
    # Specifies your App Registration's secret key:
    client-secret: ${CLIENT_SECRET}
    # Specifies the post-log-out-redirect-uri, where to return your app after logout.
    post-logout-redirect-uri: http://localhost:8080
