# src/main/resources/application.yml
# Specifies your Active Directory ID:
azure:
  activedirectory:
    tenant-id: ${TENANT_ID}
    # Specifies your App Registration's Application ID:
    client-id: ${CLIENT_ID}
    # Specifies your App Registration's secret key:
    client-secret: ${CLIENT_SECRET}
